import { SubLayout } from "@/components/sub/SubLayout";
import { AlertTriangle, ArrowRight, BarChart3, CheckCircle, Clock, FileOutput, FileText, MessageSquare, Plus, Search, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { activities, companies, getProjectRoute, getQuote, projects } from "@/data/demoUniverse";
import { useDemoProject } from "@/hooks/use-demo-project";

type FilterKey="all"|"due-soon"|"needs-rfi"|"needs-pricing"|"ready"|"awarded";
const filters:{key:FilterKey;label:string}[]=[{key:"all",label:"All"},{key:"due-soon",label:"Due Soon"},{key:"needs-rfi",label:"Needs RFI"},{key:"needs-pricing",label:"Needs Pricing"},{key:"ready",label:"Ready to Submit"},{key:"awarded",label:"Awarded"}];
export default function SubDashboardPage(){
 const [search,setSearch]=useState(""); const [filter,setFilter]=useState<FilterKey>("all"); const navigate=useNavigate(); const {setProjectId}=useDemoProject();
 const matches=(p:typeof projects[number])=>filter==="all"||(filter==="due-soon"&&!!p.bidDue)||(filter==="needs-rfi"&&p.openRfis>0)||(filter==="needs-pricing"&&["Estimate","Pricing & Margin"].includes(p.subStage))||(filter==="ready"&&p.subStatus.includes("Ready"))||(filter==="awarded"&&p.subStatus.includes("Awarded"));
 const filtered=projects.filter(p=>matches(p)&&(p.name.toLowerCase().includes(search.toLowerCase())||p.client.toLowerCase().includes(search.toLowerCase())));
 const open=(id:string)=>{const p=projects.find(item=>item.id===id);if(!p)return;setProjectId(id);navigate(getProjectRoute(p,"sub"));};
 const scored=projects.filter(p=>p.subProposalScore!=null); const avg=Math.round(scored.reduce((sum,p)=>sum+(p.subProposalScore??0),0)/scored.length);
 const cards=[{label:"Active Quotes",value:String(projects.filter(p=>!p.subStatus.includes("Awarded")).length),icon:FileText},{label:"Due This Week",value:String(projects.filter(p=>p.bidDue).length),icon:Clock},{label:"Ready to Send",value:String(projects.filter(p=>p.subStatus.includes("Ready")).length),icon:FileOutput},{label:"Avg Proposal Score",value:String(avg),icon:BarChart3},{label:"Awarded",value:String(projects.filter(p=>p.subStatus.includes("Awarded")).length),icon:TrendingUp},{label:"Open RFIs",value:String(projects.reduce((s,p)=>s+p.openRfis,0)),icon:MessageSquare}];
 return <SubLayout><div className="max-w-[1400px] p-6 lg:p-8"><div className="mb-6 flex items-center justify-between"><div><h1 className="font-display text-2xl font-bold">Dashboard</h1><p className="mt-1 text-sm text-muted-foreground">{companies.trueframe.name} — Framing Subcontractor · Cincinnati, Ohio</p></div><Button asChild size="sm"><Link to="/sub/upload"><Plus size={14}/> New Quote</Link></Button></div>
 <div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6">{cards.map(c=><div key={c.label} className="odyssey-surface rounded-xl p-4"><c.icon size={14} className="mb-2 text-primary"/><p className="font-display text-xl font-bold">{c.value}</p><p className="text-[10px] text-muted-foreground">{c.label}</p></div>)}</div>
 <div className="mb-4 flex flex-wrap items-center gap-2"><div className="flex min-w-[220px] flex-1 items-center gap-2 rounded-lg border border-border bg-card/70 px-3 py-2"><Search size={14}/><input className="flex-1 bg-transparent text-sm outline-none" placeholder="Search quotes" value={search} onChange={e=>setSearch(e.target.value)}/></div>{filters.map(f=><Button key={f.key} variant={filter===f.key?"default":"outline"} size="sm" className="h-8 text-[11px]" onClick={()=>setFilter(f.key)}>{f.label}</Button>)}</div>
 <div className="mb-6 overflow-hidden rounded-xl border border-border bg-card/75 shadow-card"><div className="flex items-center justify-between border-b border-border px-5 py-3"><h2 className="font-display text-sm font-semibold">Quotes</h2><span className="text-xs text-muted-foreground">{filtered.length} of {projects.length}</span></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border bg-muted/30">{["Project","GC / Builder","Workflow","Status","Current Quote","Score","Scope Health","Due",""].map(h=><th key={h} className="whitespace-nowrap px-4 py-2.5 text-left text-xs font-medium text-muted-foreground">{h}</th>)}</tr></thead><tbody>{filtered.map(p=>{const q=getQuote(p);return <tr key={p.id} className="border-b border-border hover:bg-muted/20"><td className="px-4 py-3"><b>{p.name}</b><span className="ml-1.5 text-[10px] text-muted-foreground">{p.jobNumber}</span></td><td className="px-4 py-3 text-xs">{companies.mayfield.name}</td><td className="px-4 py-3 text-xs">{p.subStage}</td><td className="px-4 py-3"><span className="rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-medium text-primary">{p.subStatus}</span></td><td className="px-4 py-3 font-semibold">{q.currentAmount?`$${q.currentAmount.toLocaleString()}`:"Preliminary"}</td><td className="px-4 py-3 font-semibold text-primary">{p.subProposalScore??"—"}</td><td className="px-4 py-3"><span className="rounded bg-primary/10 px-1.5 py-0.5 text-[10px] text-primary">{p.scopeCoverage}%</span></td><td className="px-4 py-3 text-xs text-muted-foreground">{p.bidDue??"—"}</td><td className="px-4 py-3"><Button variant="ghost" size="sm" onClick={()=>open(p.id)}>Open <ArrowRight size={10}/></Button></td></tr>})}</tbody></table></div></div>
 <div className="grid gap-6 lg:grid-cols-2"><div className="odyssey-surface rounded-xl p-5"><h2 className="mb-3 font-display text-sm font-semibold">Recent Activity</h2>{activities.filter(a=>a.track==="sub"||a.projectId==="fregolle").map(a=><div key={a.id} className="flex gap-3 py-2"><CheckCircle size={13} className="mt-1 text-primary"/><div><p className="text-sm">{a.text}</p><p className="text-[10px] text-muted-foreground">{a.time}</p></div></div>)}</div><div className="odyssey-surface rounded-xl p-5"><h2 className="mb-3 font-display text-sm font-semibold">Alerts & Flags</h2>{projects.filter(p=>p.attention&&!p.attention.includes("generated")).slice(0,4).map(p=><button key={p.id} onClick={()=>open(p.id)} className="mb-2 flex w-full items-center gap-2 rounded-lg bg-warning/5 p-2.5 text-left text-xs text-warning"><AlertTriangle size={12}/><span className="flex-1">{p.name}: {p.attention}</span><ArrowRight size={10}/></button>)}</div></div>
 </div></SubLayout>;
}
