import { AppLayout } from "@/components/app/AppLayout";
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3, MapPin, Plus, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { cn } from "@/lib/utils";
import { activities, companies, getProjectRoute, money, people, projects } from "@/data/demoUniverse";
import { useDemoProject } from "@/hooks/use-demo-project";

export default function DashboardPage() {
  const [query, setQuery] = useState("");
  const navigate = useNavigate();
  const { setProjectId } = useDemoProject();
  const visibleProjects = projects.filter(project => project.name.toLowerCase().includes(query.toLowerCase()) || project.client.toLowerCase().includes(query.toLowerCase()));
  const attention = projects.filter(project => project.attention).slice(0, 4);
  const openProject = (id: string) => { const project = projects.find(item => item.id === id); if (!project) return; setProjectId(id); navigate(getProjectRoute(project, "builder")); };
  return <AppLayout><div className="mx-auto w-full max-w-[1320px] p-4 lg:p-7">
    <section className="mb-7 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-[11px] font-semibold uppercase text-muted-foreground [letter-spacing:.16em]">{companies.mayfield.name} · General Contractor</p><h1 className="font-display text-3xl font-semibold text-foreground lg:text-4xl">Good afternoon, {people.frankie.firstName}</h1><p className="mt-2 text-sm text-muted-foreground">Six connected projects across preconstruction, proposals, and active construction.</p></div><Button asChild size="sm"><Link to="/app/new-project"><Plus size={14}/> New project</Link></Button></section>
    <section className="mb-7"><div className="mb-3 flex items-center justify-between px-1"><h2 className="text-[11px] font-bold uppercase text-muted-foreground [letter-spacing:.16em]">Project portfolio</h2><div className="flex items-center gap-3"><div className="flex h-8 items-center gap-2 rounded-full border border-border/60 bg-card/45 px-3 backdrop-blur-md"><Search size={13} className="text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-36 bg-transparent text-xs outline-none" placeholder="Find a project"/></div><span className="text-[11px] font-semibold text-muted-foreground">{visibleProjects.length} projects</span></div></div>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visibleProjects.map(project=><button key={project.id} onClick={()=>openProject(project.id)} className="odyssey-surface group relative overflow-hidden rounded-2xl p-5 text-left transition-all hover:-translate-y-0.5 hover:shadow-card-hover"><div className={cn("absolute inset-x-0 top-0 h-1",project.builderStatus.includes("Ready")?"bg-success/55":project.attention.includes("below")||project.attention.includes("exceeds")?"bg-destructive/55":"bg-primary/35")}/><div className="mb-5 flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate text-sm font-bold">{project.name}</h3><p className="mt-1 text-[10px] font-semibold uppercase text-muted-foreground">{project.jobNumber} · {project.type}</p></div><span className="shrink-0 rounded-full bg-secondary/80 px-2.5 py-1 text-[9px] font-bold uppercase">{project.builderStatus}</span></div><div className="space-y-3"><div className="flex items-center justify-between text-[11px]"><span className="font-semibold uppercase text-muted-foreground">{project.builderStage}</span><span className="flex items-center gap-1.5 text-muted-foreground"><MapPin size={12}/>{project.location}</span></div><div className="grid grid-cols-3 gap-2 border-t border-border/50 pt-4 text-[10px]"><span><b className="block text-foreground">{money(project.builderCost)}</b>Cost</span><span><b className="block text-foreground">{money(project.clientPrice)}</b>Client</span><span><b className="block text-foreground">{project.proposalScore ?? "—"}</b>Score</span></div><p className="flex items-center gap-1 font-semibold text-primary">{project.attention.includes("generated")?<CheckCircle2 size={12}/>:<AlertTriangle size={12}/>} {project.attention}</p></div></button>)}</div>
    </section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="odyssey-surface overflow-hidden rounded-2xl"><div className="flex items-center justify-between border-b border-border/55 px-5 py-4"><h2 className="text-xs font-bold uppercase">Attention needed</h2><span className="rounded-full bg-destructive px-2 py-0.5 text-[9px] font-bold text-destructive-foreground">{attention.length}</span></div>{attention.map(project=><button key={project.id} onClick={()=>openProject(project.id)} className="group flex w-full items-center gap-4 border-b border-border/50 px-5 py-4 text-left hover:bg-card/45"><span className="h-2 w-2 rounded-full bg-warning"/><span className="flex-1"><b className="block text-sm">{project.name}</b><span className="text-[10px] text-muted-foreground">{project.attention}</span></span><ArrowRight size={14}/></button>)}</div><div className="odyssey-surface overflow-hidden rounded-2xl"><div className="border-b border-border/55 px-5 py-4"><h2 className="text-xs font-bold uppercase">Recent activity</h2></div>{activities.filter(a=>a.track==="builder").map(activity=><div key={activity.id} className="flex gap-3 border-b border-border/50 px-5 py-4"><Clock3 size={13} className="mt-0.5 text-primary"/><div><p className="text-sm font-semibold">{activity.text}</p><p className="text-[10px] text-muted-foreground">{activity.time}</p></div></div>)}</div></section>
  </div></AppLayout>;
}
